
# data hparams
data_dir: '/gscratch/scrubbed/gvisan01/data/zernicke'
neigh_kind: 'no_residue-yes_sidechain'
n_train_neigh: 2934478
n_valid_neigh: 721845
n_test_neigh: 41931
rcut: 10.0
lmax: 5
rmax: 20
n_channels: 7
rst_normalization: 'square'
get_H: true
get_SASA: true
get_charge: true
normalize_input: false

# model hparams
model_type: 'cgnet'
model_hparams: 
  output_dim: 20
  n_cg_blocks: 5
  n_fc_blocks:
  h_dim: 
  fc_nonlin:
  dropout_rate:
  ch_size_list:
  ls_nonlin_rule_list:
  ch_nonlin_rule_list:
  do_initial_linear_projection:
  ch_initial_linear_projection:
  lmax_list:
  use_additive_skip_connections:
  use_batch_norm:
  weights_initializer:
  norm_type:
  normalization:
  norm_balanced:
  norm_affine:
  norm_nonlinearity:
  norm_location:
  linearity_first:
  filter_symmetric:

# training hparams
n_epochs: 5
lr: 0.001
lr_scheduler: 'reduce_lr_on_plateau'
batch_size: 512

# rng seed, for reproducibility
seed: 123456789
